# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018
  project: Supersized - full screen background slideshow
  version: 1.1
  release: 1.1.0
  latex_documents:
  - - Index
    - frsupersized.tex
    - Supersized - full screen background slideshow
    - Frank Frewer
    - manual
  html_theme_options:
    github_repository: ffrewer/frsupersized
    github_branch: 1.1.0
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...